services:
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    ports:
      - "19092:19092"
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./secrets/kafka:/opt/kafka/secrets:ro
    networks:
      - kafka-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENERS: >-
        CONTROLLER://:9093,
        INTERNAL://:9092,
        EXTERNAL://:19092

      KAFKA_ADVERTISED_LISTENERS: >-
        INTERNAL://kafka:9092,
        EXTERNAL://localhost:19092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
        CONTROLLER:PLAINTEXT,
        INTERNAL:SSL,
        EXTERNAL:SSL

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_SSL_KEYSTORE_LOCATION: /opt/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: VeryStrongPass123
      KAFKA_SSL_KEY_PASSWORD: VeryStrongPass123
      KAFKA_SSL_KEYSTORE_TYPE: JKS
      KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/kafka/secrets/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: VeryStrongPass123
      KAFKA_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    volumes:
      - ./secrets/kafka:/opt/kafka/secrets:ro
    networks:
      - kafka-net
    environment:
      KAFKA_CLUSTERS_0_NAME: local-ssl
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORE_LOCATION: /opt/kafka/secrets/kafka.truststore.jks
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORE_PASSWORD: VeryStrongPass123

      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /opt/kafka/secrets/kafka.keystore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: VeryStrongPass123
      KAFKA_CLUSTERS_0_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""

volumes:
  kafka-data:

networks:
  kafka-net:
